/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SavesSaveIdEmpire_budgetRouteImport } from './routes/saves/$saveId/empire_budget'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SavesSaveIdEmpire_budgetRoute =
  SavesSaveIdEmpire_budgetRouteImport.update({
    id: '/saves/$saveId/empire_budget',
    path: '/saves/$saveId/empire_budget',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/saves/$saveId/empire_budget': typeof SavesSaveIdEmpire_budgetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/saves/$saveId/empire_budget': typeof SavesSaveIdEmpire_budgetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/saves/$saveId/empire_budget': typeof SavesSaveIdEmpire_budgetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/saves/$saveId/empire_budget'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/saves/$saveId/empire_budget'
  id: '__root__' | '/' | '/saves/$saveId/empire_budget'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SavesSaveIdEmpire_budgetRoute: typeof SavesSaveIdEmpire_budgetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saves/$saveId/empire_budget': {
      id: '/saves/$saveId/empire_budget'
      path: '/saves/$saveId/empire_budget'
      fullPath: '/saves/$saveId/empire_budget'
      preLoaderRoute: typeof SavesSaveIdEmpire_budgetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SavesSaveIdEmpire_budgetRoute: SavesSaveIdEmpire_budgetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
