import { Budget, BudgetEntry } from './graphql/generated/types.js'

const emptyBudgetEntry: BudgetEntry = {
  alloys: 0,
  consumerGoods: 0,
  energy: 0,
  engineeringResearch: 0,
  food: 0,
  influence: 0,
  minerals: 0,
  physicsResearch: 0,
  societyResearch: 0,
  trade: 0,
  unity: 0,
}

export const emptyBudget: Budget = {
  armies: emptyBudgetEntry,
  countryBase: emptyBudgetEntry,
  countryPowerProjection: emptyBudgetEntry,
  leaderCommanders: emptyBudgetEntry,
  leaderOfficials: emptyBudgetEntry,
  leaderScientists: emptyBudgetEntry,
  orbitalMiningDeposits: emptyBudgetEntry,
  orbitalResearchDeposits: emptyBudgetEntry,
  planetArtisans: emptyBudgetEntry,
  planetBiologists: emptyBudgetEntry,
  planetBuildings: emptyBudgetEntry,
  planetBuildingsStrongholds: emptyBudgetEntry,
  planetBureaucrats: emptyBudgetEntry,
  planetDistrictsCities: emptyBudgetEntry,
  planetDistrictsFarming: emptyBudgetEntry,
  planetDistrictsGenerator: emptyBudgetEntry,
  planetDistrictsMining: emptyBudgetEntry,
  planetDoctors: emptyBudgetEntry,
  planetEngineers: emptyBudgetEntry,
  planetFarmers: emptyBudgetEntry,
  planetJobs: emptyBudgetEntry,
  planetMetallurgists: emptyBudgetEntry,
  planetMiners: emptyBudgetEntry,
  planetPhysicists: emptyBudgetEntry,
  planetPoliticians: emptyBudgetEntry,
  planetPops: emptyBudgetEntry,
  planetResourceDeficit: emptyBudgetEntry,
  planetTechnician: emptyBudgetEntry,
  planetTraders: emptyBudgetEntry,
  popCategoryRulers: emptyBudgetEntry,
  popCategorySpecialists: emptyBudgetEntry,
  popCategoryWorkers: emptyBudgetEntry,
  popFactions: emptyBudgetEntry,
  shipComponents: emptyBudgetEntry,
  ships: emptyBudgetEntry,
  starbaseBuildings: emptyBudgetEntry,
  starbaseModules: emptyBudgetEntry,
  starbases: emptyBudgetEntry,
  stationGatherers: emptyBudgetEntry,
  stationResearchers: emptyBudgetEntry,
  tradePolicy: emptyBudgetEntry,
}
