# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class BudgetEntryFields(BaseModel):
    alloys: Optional[float]
    astral_threads: Optional[float] = Field(alias="astralThreads")
    consumer_goods: Optional[float] = Field(alias="consumerGoods")
    energy: Optional[float]
    engineering_research: Optional[float] = Field(alias="engineeringResearch")
    exotic_gases: Optional[float] = Field(alias="exoticGases")
    food: Optional[float]
    influence: Optional[float]
    minerals: Optional[float]
    minor_artifacts: Optional[float] = Field(alias="minorArtifacts")
    nanites: Optional[float]
    physics_research: Optional[float] = Field(alias="physicsResearch")
    rare_crystals: Optional[float] = Field(alias="rareCrystals")
    society_research: Optional[float] = Field(alias="societyResearch")
    sr_dark_matter: Optional[float] = Field(alias="srDarkMatter")
    sr_living_metal: Optional[float] = Field(alias="srLivingMetal")
    sr_zro: Optional[float] = Field(alias="srZro")
    trade: Optional[float]
    unity: Optional[float]
    volatile_motes: Optional[float] = Field(alias="volatileMotes")


class BudgetCategoryFields(BaseModel):
    armies: Optional["BudgetCategoryFieldsArmies"]
    colonies: Optional["BudgetCategoryFieldsColonies"]
    commercial_pacts: Optional["BudgetCategoryFieldsCommercialPacts"] = Field(
        alias="commercialPacts"
    )
    country_agendas: Optional["BudgetCategoryFieldsCountryAgendas"] = Field(
        alias="countryAgendas"
    )
    country_base: Optional["BudgetCategoryFieldsCountryBase"] = Field(
        alias="countryBase"
    )
    country_civics: Optional["BudgetCategoryFieldsCountryCivics"] = Field(
        alias="countryCivics"
    )
    country_dessanu: Optional["BudgetCategoryFieldsCountryDessanu"] = Field(
        alias="countryDessanu"
    )
    country_ethic: Optional["BudgetCategoryFieldsCountryEthic"] = Field(
        alias="countryEthic"
    )
    country_power_projection: Optional["BudgetCategoryFieldsCountryPowerProjection"] = (
        Field(alias="countryPowerProjection")
    )
    country_ruler: Optional["BudgetCategoryFieldsCountryRuler"] = Field(
        alias="countryRuler"
    )
    edicts: Optional["BudgetCategoryFieldsEdicts"]
    leader_commanders: Optional["BudgetCategoryFieldsLeaderCommanders"] = Field(
        alias="leaderCommanders"
    )
    leader_officials: Optional["BudgetCategoryFieldsLeaderOfficials"] = Field(
        alias="leaderOfficials"
    )
    leader_scientists: Optional["BudgetCategoryFieldsLeaderScientists"] = Field(
        alias="leaderScientists"
    )
    megastructures: Optional["BudgetCategoryFieldsMegastructures"]
    megastructures_grand_archive: Optional[
        "BudgetCategoryFieldsMegastructuresGrandArchive"
    ] = Field(alias="megastructuresGrandArchive")
    megastructures_habitat: Optional["BudgetCategoryFieldsMegastructuresHabitat"] = (
        Field(alias="megastructuresHabitat")
    )
    megastructures_hyper_relay: Optional[
        "BudgetCategoryFieldsMegastructuresHyperRelay"
    ] = Field(alias="megastructuresHyperRelay")
    migration_pacts: Optional["BudgetCategoryFieldsMigrationPacts"] = Field(
        alias="migrationPacts"
    )
    none: Optional["BudgetCategoryFieldsNone"]
    orbital_mining_deposits: Optional["BudgetCategoryFieldsOrbitalMiningDeposits"] = (
        Field(alias="orbitalMiningDeposits")
    )
    orbital_research_deposits: Optional[
        "BudgetCategoryFieldsOrbitalResearchDeposits"
    ] = Field(alias="orbitalResearchDeposits")
    overlord_subsidy: Optional["BudgetCategoryFieldsOverlordSubsidy"] = Field(
        alias="overlordSubsidy"
    )
    planet_artisans: Optional["BudgetCategoryFieldsPlanetArtisans"] = Field(
        alias="planetArtisans"
    )
    planet_biologists: Optional["BudgetCategoryFieldsPlanetBiologists"] = Field(
        alias="planetBiologists"
    )
    planet_buildings: Optional["BudgetCategoryFieldsPlanetBuildings"] = Field(
        alias="planetBuildings"
    )
    planet_buildings_clone_vats: Optional[
        "BudgetCategoryFieldsPlanetBuildingsCloneVats"
    ] = Field(alias="planetBuildingsCloneVats")
    planet_buildings_hab_capital: Optional[
        "BudgetCategoryFieldsPlanetBuildingsHabCapital"
    ] = Field(alias="planetBuildingsHabCapital")
    planet_buildings_storm_tech: Optional[
        "BudgetCategoryFieldsPlanetBuildingsStormTech"
    ] = Field(alias="planetBuildingsStormTech")
    planet_buildings_strongholds: Optional[
        "BudgetCategoryFieldsPlanetBuildingsStrongholds"
    ] = Field(alias="planetBuildingsStrongholds")
    planet_bureaucrats: Optional["BudgetCategoryFieldsPlanetBureaucrats"] = Field(
        alias="planetBureaucrats"
    )
    planet_civilians: Optional["BudgetCategoryFieldsPlanetCivilians"] = Field(
        alias="planetCivilians"
    )
    planet_clerks: Optional["BudgetCategoryFieldsPlanetClerks"] = Field(
        alias="planetClerks"
    )
    planet_deposits: Optional["BudgetCategoryFieldsPlanetDeposits"] = Field(
        alias="planetDeposits"
    )
    planet_districts: Optional["BudgetCategoryFieldsPlanetDistricts"] = Field(
        alias="planetDistricts"
    )
    planet_districts_cities: Optional["BudgetCategoryFieldsPlanetDistrictsCities"] = (
        Field(alias="planetDistrictsCities")
    )
    planet_districts_farming: Optional["BudgetCategoryFieldsPlanetDistrictsFarming"] = (
        Field(alias="planetDistrictsFarming")
    )
    planet_districts_generator: Optional[
        "BudgetCategoryFieldsPlanetDistrictsGenerator"
    ] = Field(alias="planetDistrictsGenerator")
    planet_districts_hab: Optional["BudgetCategoryFieldsPlanetDistrictsHab"] = Field(
        alias="planetDistrictsHab"
    )
    planet_districts_mining: Optional["BudgetCategoryFieldsPlanetDistrictsMining"] = (
        Field(alias="planetDistrictsMining")
    )
    planet_doctors: Optional["BudgetCategoryFieldsPlanetDoctors"] = Field(
        alias="planetDoctors"
    )
    planet_energy_thralls: Optional["BudgetCategoryFieldsPlanetEnergyThralls"] = Field(
        alias="planetEnergyThralls"
    )
    planet_engineers: Optional["BudgetCategoryFieldsPlanetEngineers"] = Field(
        alias="planetEngineers"
    )
    planet_entertainers: Optional["BudgetCategoryFieldsPlanetEntertainers"] = Field(
        alias="planetEntertainers"
    )
    planet_farmers: Optional["BudgetCategoryFieldsPlanetFarmers"] = Field(
        alias="planetFarmers"
    )
    planet_jobs: Optional["BudgetCategoryFieldsPlanetJobs"] = Field(alias="planetJobs")
    planet_jobs_productive: Optional["BudgetCategoryFieldsPlanetJobsProductive"] = (
        Field(alias="planetJobsProductive")
    )
    planet_maintenance_drones: Optional[
        "BudgetCategoryFieldsPlanetMaintenanceDrones"
    ] = Field(alias="planetMaintenanceDrones")
    planet_metallurgists: Optional["BudgetCategoryFieldsPlanetMetallurgists"] = Field(
        alias="planetMetallurgists"
    )
    planet_miners: Optional["BudgetCategoryFieldsPlanetMiners"] = Field(
        alias="planetMiners"
    )
    planet_physicists: Optional["BudgetCategoryFieldsPlanetPhysicists"] = Field(
        alias="planetPhysicists"
    )
    planet_politicians: Optional["BudgetCategoryFieldsPlanetPoliticians"] = Field(
        alias="planetPoliticians"
    )
    planet_pop_assemblers: Optional["BudgetCategoryFieldsPlanetPopAssemblers"] = Field(
        alias="planetPopAssemblers"
    )
    planet_pops: Optional["BudgetCategoryFieldsPlanetPops"] = Field(alias="planetPops")
    planet_resource_deficit: Optional["BudgetCategoryFieldsPlanetResourceDeficit"] = (
        Field(alias="planetResourceDeficit")
    )
    planet_sr_miners: Optional["BudgetCategoryFieldsPlanetSrMiners"] = Field(
        alias="planetSrMiners"
    )
    planet_technician: Optional["BudgetCategoryFieldsPlanetTechnician"] = Field(
        alias="planetTechnician"
    )
    planet_traders: Optional["BudgetCategoryFieldsPlanetTraders"] = Field(
        alias="planetTraders"
    )
    pop_category_civilians: Optional["BudgetCategoryFieldsPopCategoryCivilians"] = (
        Field(alias="popCategoryCivilians")
    )
    pop_category_drones: Optional["BudgetCategoryFieldsPopCategoryDrones"] = Field(
        alias="popCategoryDrones"
    )
    pop_category_rulers: Optional["BudgetCategoryFieldsPopCategoryRulers"] = Field(
        alias="popCategoryRulers"
    )
    pop_category_specialists: Optional["BudgetCategoryFieldsPopCategorySpecialists"] = (
        Field(alias="popCategorySpecialists")
    )
    pop_category_workers: Optional["BudgetCategoryFieldsPopCategoryWorkers"] = Field(
        alias="popCategoryWorkers"
    )
    pop_factions: Optional["BudgetCategoryFieldsPopFactions"] = Field(
        alias="popFactions"
    )
    ship_components: Optional["BudgetCategoryFieldsShipComponents"] = Field(
        alias="shipComponents"
    )
    ships: Optional["BudgetCategoryFieldsShips"]
    situations: Optional["BudgetCategoryFieldsSituations"]
    starbase_buildings: Optional["BudgetCategoryFieldsStarbaseBuildings"] = Field(
        alias="starbaseBuildings"
    )
    starbase_modules: Optional["BudgetCategoryFieldsStarbaseModules"] = Field(
        alias="starbaseModules"
    )
    starbases: Optional["BudgetCategoryFieldsStarbases"]
    station_gatherers: Optional["BudgetCategoryFieldsStationGatherers"] = Field(
        alias="stationGatherers"
    )
    station_observer_missions: Optional[
        "BudgetCategoryFieldsStationObserverMissions"
    ] = Field(alias="stationObserverMissions")
    station_observers: Optional["BudgetCategoryFieldsStationObservers"] = Field(
        alias="stationObservers"
    )
    station_researchers: Optional["BudgetCategoryFieldsStationResearchers"] = Field(
        alias="stationResearchers"
    )
    trade_policy: Optional["BudgetCategoryFieldsTradePolicy"] = Field(
        alias="tradePolicy"
    )


class BudgetCategoryFieldsArmies(BudgetEntryFields):
    pass


class BudgetCategoryFieldsColonies(BudgetEntryFields):
    pass


class BudgetCategoryFieldsCommercialPacts(BudgetEntryFields):
    pass


class BudgetCategoryFieldsCountryAgendas(BudgetEntryFields):
    pass


class BudgetCategoryFieldsCountryBase(BudgetEntryFields):
    pass


class BudgetCategoryFieldsCountryCivics(BudgetEntryFields):
    pass


class BudgetCategoryFieldsCountryDessanu(BudgetEntryFields):
    pass


class BudgetCategoryFieldsCountryEthic(BudgetEntryFields):
    pass


class BudgetCategoryFieldsCountryPowerProjection(BudgetEntryFields):
    pass


class BudgetCategoryFieldsCountryRuler(BudgetEntryFields):
    pass


class BudgetCategoryFieldsEdicts(BudgetEntryFields):
    pass


class BudgetCategoryFieldsLeaderCommanders(BudgetEntryFields):
    pass


class BudgetCategoryFieldsLeaderOfficials(BudgetEntryFields):
    pass


class BudgetCategoryFieldsLeaderScientists(BudgetEntryFields):
    pass


class BudgetCategoryFieldsMegastructures(BudgetEntryFields):
    pass


class BudgetCategoryFieldsMegastructuresGrandArchive(BudgetEntryFields):
    pass


class BudgetCategoryFieldsMegastructuresHabitat(BudgetEntryFields):
    pass


class BudgetCategoryFieldsMegastructuresHyperRelay(BudgetEntryFields):
    pass


class BudgetCategoryFieldsMigrationPacts(BudgetEntryFields):
    pass


class BudgetCategoryFieldsNone(BudgetEntryFields):
    pass


class BudgetCategoryFieldsOrbitalMiningDeposits(BudgetEntryFields):
    pass


class BudgetCategoryFieldsOrbitalResearchDeposits(BudgetEntryFields):
    pass


class BudgetCategoryFieldsOverlordSubsidy(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetArtisans(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetBiologists(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetBuildings(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetBuildingsCloneVats(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetBuildingsHabCapital(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetBuildingsStormTech(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetBuildingsStrongholds(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetBureaucrats(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetCivilians(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetClerks(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetDeposits(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetDistricts(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetDistrictsCities(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetDistrictsFarming(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetDistrictsGenerator(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetDistrictsHab(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetDistrictsMining(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetDoctors(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetEnergyThralls(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetEngineers(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetEntertainers(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetFarmers(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetJobs(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetJobsProductive(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetMaintenanceDrones(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetMetallurgists(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetMiners(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetPhysicists(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetPoliticians(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetPopAssemblers(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetPops(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetResourceDeficit(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetSrMiners(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetTechnician(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetTraders(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPopCategoryCivilians(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPopCategoryDrones(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPopCategoryRulers(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPopCategorySpecialists(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPopCategoryWorkers(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPopFactions(BudgetEntryFields):
    pass


class BudgetCategoryFieldsShipComponents(BudgetEntryFields):
    pass


class BudgetCategoryFieldsShips(BudgetEntryFields):
    pass


class BudgetCategoryFieldsSituations(BudgetEntryFields):
    pass


class BudgetCategoryFieldsStarbaseBuildings(BudgetEntryFields):
    pass


class BudgetCategoryFieldsStarbaseModules(BudgetEntryFields):
    pass


class BudgetCategoryFieldsStarbases(BudgetEntryFields):
    pass


class BudgetCategoryFieldsStationGatherers(BudgetEntryFields):
    pass


class BudgetCategoryFieldsStationObserverMissions(BudgetEntryFields):
    pass


class BudgetCategoryFieldsStationObservers(BudgetEntryFields):
    pass


class BudgetCategoryFieldsStationResearchers(BudgetEntryFields):
    pass


class BudgetCategoryFieldsTradePolicy(BudgetEntryFields):
    pass


BudgetEntryFields.model_rebuild()
BudgetCategoryFields.model_rebuild()
