# Generated by ariadne-codegen
# Source: queries.graphql


from pydantic import Field

from .base_model import BaseModel


class BudgetEntryFields(BaseModel):
    alloys: float | None
    astral_threads: float | None = Field(alias="astralThreads")
    consumer_goods: float | None = Field(alias="consumerGoods")
    energy: float | None
    engineering_research: float | None = Field(alias="engineeringResearch")
    exotic_gases: float | None = Field(alias="exoticGases")
    food: float | None
    influence: float | None
    minerals: float | None
    minor_artifacts: float | None = Field(alias="minorArtifacts")
    nanites: float | None
    physics_research: float | None = Field(alias="physicsResearch")
    rare_crystals: float | None = Field(alias="rareCrystals")
    society_research: float | None = Field(alias="societyResearch")
    sr_dark_matter: float | None = Field(alias="srDarkMatter")
    sr_living_metal: float | None = Field(alias="srLivingMetal")
    sr_zro: float | None = Field(alias="srZro")
    trade: float | None
    unity: float | None
    volatile_motes: float | None = Field(alias="volatileMotes")


class BudgetCategoryFields(BaseModel):
    armies: BudgetCategoryFieldsArmies | None
    colonies: BudgetCategoryFieldsColonies | None
    commercial_pacts: BudgetCategoryFieldsCommercialPacts | None = Field(
        alias="commercialPacts",
    )
    country_agendas: BudgetCategoryFieldsCountryAgendas | None = Field(
        alias="countryAgendas",
    )
    country_base: BudgetCategoryFieldsCountryBase | None = Field(
        alias="countryBase",
    )
    country_civics: BudgetCategoryFieldsCountryCivics | None = Field(
        alias="countryCivics",
    )
    country_dessanu: BudgetCategoryFieldsCountryDessanu | None = Field(
        alias="countryDessanu",
    )
    country_ethic: BudgetCategoryFieldsCountryEthic | None = Field(
        alias="countryEthic",
    )
    country_power_projection: BudgetCategoryFieldsCountryPowerProjection | None = (
        Field(alias="countryPowerProjection")
    )
    country_ruler: BudgetCategoryFieldsCountryRuler | None = Field(
        alias="countryRuler",
    )
    edicts: BudgetCategoryFieldsEdicts | None
    leader_commanders: BudgetCategoryFieldsLeaderCommanders | None = Field(
        alias="leaderCommanders",
    )
    leader_officials: BudgetCategoryFieldsLeaderOfficials | None = Field(
        alias="leaderOfficials",
    )
    leader_scientists: BudgetCategoryFieldsLeaderScientists | None = Field(
        alias="leaderScientists",
    )
    megastructures: BudgetCategoryFieldsMegastructures | None
    megastructures_grand_archive: BudgetCategoryFieldsMegastructuresGrandArchive | None = Field(alias="megastructuresGrandArchive")
    megastructures_habitat: BudgetCategoryFieldsMegastructuresHabitat | None = (
        Field(alias="megastructuresHabitat")
    )
    megastructures_hyper_relay: BudgetCategoryFieldsMegastructuresHyperRelay | None = Field(alias="megastructuresHyperRelay")
    migration_pacts: BudgetCategoryFieldsMigrationPacts | None = Field(
        alias="migrationPacts",
    )
    none: BudgetCategoryFieldsNone | None
    orbital_mining_deposits: BudgetCategoryFieldsOrbitalMiningDeposits | None = (
        Field(alias="orbitalMiningDeposits")
    )
    orbital_research_deposits: BudgetCategoryFieldsOrbitalResearchDeposits | None = Field(alias="orbitalResearchDeposits")
    overlord_subsidy: BudgetCategoryFieldsOverlordSubsidy | None = Field(
        alias="overlordSubsidy",
    )
    planet_artisans: BudgetCategoryFieldsPlanetArtisans | None = Field(
        alias="planetArtisans",
    )
    planet_biologists: BudgetCategoryFieldsPlanetBiologists | None = Field(
        alias="planetBiologists",
    )
    planet_buildings: BudgetCategoryFieldsPlanetBuildings | None = Field(
        alias="planetBuildings",
    )
    planet_buildings_clone_vats: BudgetCategoryFieldsPlanetBuildingsCloneVats | None = Field(alias="planetBuildingsCloneVats")
    planet_buildings_hab_capital: BudgetCategoryFieldsPlanetBuildingsHabCapital | None = Field(alias="planetBuildingsHabCapital")
    planet_buildings_storm_tech: BudgetCategoryFieldsPlanetBuildingsStormTech | None = Field(alias="planetBuildingsStormTech")
    planet_buildings_strongholds: BudgetCategoryFieldsPlanetBuildingsStrongholds | None = Field(alias="planetBuildingsStrongholds")
    planet_bureaucrats: BudgetCategoryFieldsPlanetBureaucrats | None = Field(
        alias="planetBureaucrats",
    )
    planet_civilians: BudgetCategoryFieldsPlanetCivilians | None = Field(
        alias="planetCivilians",
    )
    planet_clerks: BudgetCategoryFieldsPlanetClerks | None = Field(
        alias="planetClerks",
    )
    planet_deposits: BudgetCategoryFieldsPlanetDeposits | None = Field(
        alias="planetDeposits",
    )
    planet_districts: BudgetCategoryFieldsPlanetDistricts | None = Field(
        alias="planetDistricts",
    )
    planet_districts_cities: BudgetCategoryFieldsPlanetDistrictsCities | None = (
        Field(alias="planetDistrictsCities")
    )
    planet_districts_farming: BudgetCategoryFieldsPlanetDistrictsFarming | None = (
        Field(alias="planetDistrictsFarming")
    )
    planet_districts_generator: BudgetCategoryFieldsPlanetDistrictsGenerator | None = Field(alias="planetDistrictsGenerator")
    planet_districts_hab: BudgetCategoryFieldsPlanetDistrictsHab | None = Field(
        alias="planetDistrictsHab",
    )
    planet_districts_mining: BudgetCategoryFieldsPlanetDistrictsMining | None = (
        Field(alias="planetDistrictsMining")
    )
    planet_doctors: BudgetCategoryFieldsPlanetDoctors | None = Field(
        alias="planetDoctors",
    )
    planet_energy_thralls: BudgetCategoryFieldsPlanetEnergyThralls | None = Field(
        alias="planetEnergyThralls",
    )
    planet_engineers: BudgetCategoryFieldsPlanetEngineers | None = Field(
        alias="planetEngineers",
    )
    planet_entertainers: BudgetCategoryFieldsPlanetEntertainers | None = Field(
        alias="planetEntertainers",
    )
    planet_farmers: BudgetCategoryFieldsPlanetFarmers | None = Field(
        alias="planetFarmers",
    )
    planet_jobs: BudgetCategoryFieldsPlanetJobs | None = Field(alias="planetJobs")
    planet_jobs_productive: BudgetCategoryFieldsPlanetJobsProductive | None = (
        Field(alias="planetJobsProductive")
    )
    planet_maintenance_drones: BudgetCategoryFieldsPlanetMaintenanceDrones | None = Field(alias="planetMaintenanceDrones")
    planet_metallurgists: BudgetCategoryFieldsPlanetMetallurgists | None = Field(
        alias="planetMetallurgists",
    )
    planet_miners: BudgetCategoryFieldsPlanetMiners | None = Field(
        alias="planetMiners",
    )
    planet_physicists: BudgetCategoryFieldsPlanetPhysicists | None = Field(
        alias="planetPhysicists",
    )
    planet_politicians: BudgetCategoryFieldsPlanetPoliticians | None = Field(
        alias="planetPoliticians",
    )
    planet_pop_assemblers: BudgetCategoryFieldsPlanetPopAssemblers | None = Field(
        alias="planetPopAssemblers",
    )
    planet_pops: BudgetCategoryFieldsPlanetPops | None = Field(alias="planetPops")
    planet_resource_deficit: BudgetCategoryFieldsPlanetResourceDeficit | None = (
        Field(alias="planetResourceDeficit")
    )
    planet_sr_miners: BudgetCategoryFieldsPlanetSrMiners | None = Field(
        alias="planetSrMiners",
    )
    planet_technician: BudgetCategoryFieldsPlanetTechnician | None = Field(
        alias="planetTechnician",
    )
    planet_traders: BudgetCategoryFieldsPlanetTraders | None = Field(
        alias="planetTraders",
    )
    pop_category_civilians: BudgetCategoryFieldsPopCategoryCivilians | None = (
        Field(alias="popCategoryCivilians")
    )
    pop_category_drones: BudgetCategoryFieldsPopCategoryDrones | None = Field(
        alias="popCategoryDrones",
    )
    pop_category_rulers: BudgetCategoryFieldsPopCategoryRulers | None = Field(
        alias="popCategoryRulers",
    )
    pop_category_specialists: BudgetCategoryFieldsPopCategorySpecialists | None = (
        Field(alias="popCategorySpecialists")
    )
    pop_category_workers: BudgetCategoryFieldsPopCategoryWorkers | None = Field(
        alias="popCategoryWorkers",
    )
    pop_factions: BudgetCategoryFieldsPopFactions | None = Field(
        alias="popFactions",
    )
    ship_components: BudgetCategoryFieldsShipComponents | None = Field(
        alias="shipComponents",
    )
    ships: BudgetCategoryFieldsShips | None
    situations: BudgetCategoryFieldsSituations | None
    starbase_buildings: BudgetCategoryFieldsStarbaseBuildings | None = Field(
        alias="starbaseBuildings",
    )
    starbase_modules: BudgetCategoryFieldsStarbaseModules | None = Field(
        alias="starbaseModules",
    )
    starbases: BudgetCategoryFieldsStarbases | None
    station_gatherers: BudgetCategoryFieldsStationGatherers | None = Field(
        alias="stationGatherers",
    )
    station_observer_missions: BudgetCategoryFieldsStationObserverMissions | None = Field(alias="stationObserverMissions")
    station_observers: BudgetCategoryFieldsStationObservers | None = Field(
        alias="stationObservers",
    )
    station_researchers: BudgetCategoryFieldsStationResearchers | None = Field(
        alias="stationResearchers",
    )
    trade_policy: BudgetCategoryFieldsTradePolicy | None = Field(
        alias="tradePolicy",
    )


class BudgetCategoryFieldsArmies(BudgetEntryFields):
    pass


class BudgetCategoryFieldsColonies(BudgetEntryFields):
    pass


class BudgetCategoryFieldsCommercialPacts(BudgetEntryFields):
    pass


class BudgetCategoryFieldsCountryAgendas(BudgetEntryFields):
    pass


class BudgetCategoryFieldsCountryBase(BudgetEntryFields):
    pass


class BudgetCategoryFieldsCountryCivics(BudgetEntryFields):
    pass


class BudgetCategoryFieldsCountryDessanu(BudgetEntryFields):
    pass


class BudgetCategoryFieldsCountryEthic(BudgetEntryFields):
    pass


class BudgetCategoryFieldsCountryPowerProjection(BudgetEntryFields):
    pass


class BudgetCategoryFieldsCountryRuler(BudgetEntryFields):
    pass


class BudgetCategoryFieldsEdicts(BudgetEntryFields):
    pass


class BudgetCategoryFieldsLeaderCommanders(BudgetEntryFields):
    pass


class BudgetCategoryFieldsLeaderOfficials(BudgetEntryFields):
    pass


class BudgetCategoryFieldsLeaderScientists(BudgetEntryFields):
    pass


class BudgetCategoryFieldsMegastructures(BudgetEntryFields):
    pass


class BudgetCategoryFieldsMegastructuresGrandArchive(BudgetEntryFields):
    pass


class BudgetCategoryFieldsMegastructuresHabitat(BudgetEntryFields):
    pass


class BudgetCategoryFieldsMegastructuresHyperRelay(BudgetEntryFields):
    pass


class BudgetCategoryFieldsMigrationPacts(BudgetEntryFields):
    pass


class BudgetCategoryFieldsNone(BudgetEntryFields):
    pass


class BudgetCategoryFieldsOrbitalMiningDeposits(BudgetEntryFields):
    pass


class BudgetCategoryFieldsOrbitalResearchDeposits(BudgetEntryFields):
    pass


class BudgetCategoryFieldsOverlordSubsidy(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetArtisans(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetBiologists(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetBuildings(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetBuildingsCloneVats(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetBuildingsHabCapital(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetBuildingsStormTech(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetBuildingsStrongholds(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetBureaucrats(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetCivilians(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetClerks(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetDeposits(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetDistricts(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetDistrictsCities(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetDistrictsFarming(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetDistrictsGenerator(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetDistrictsHab(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetDistrictsMining(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetDoctors(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetEnergyThralls(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetEngineers(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetEntertainers(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetFarmers(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetJobs(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetJobsProductive(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetMaintenanceDrones(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetMetallurgists(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetMiners(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetPhysicists(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetPoliticians(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetPopAssemblers(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetPops(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetResourceDeficit(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetSrMiners(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetTechnician(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPlanetTraders(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPopCategoryCivilians(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPopCategoryDrones(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPopCategoryRulers(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPopCategorySpecialists(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPopCategoryWorkers(BudgetEntryFields):
    pass


class BudgetCategoryFieldsPopFactions(BudgetEntryFields):
    pass


class BudgetCategoryFieldsShipComponents(BudgetEntryFields):
    pass


class BudgetCategoryFieldsShips(BudgetEntryFields):
    pass


class BudgetCategoryFieldsSituations(BudgetEntryFields):
    pass


class BudgetCategoryFieldsStarbaseBuildings(BudgetEntryFields):
    pass


class BudgetCategoryFieldsStarbaseModules(BudgetEntryFields):
    pass


class BudgetCategoryFieldsStarbases(BudgetEntryFields):
    pass


class BudgetCategoryFieldsStationGatherers(BudgetEntryFields):
    pass


class BudgetCategoryFieldsStationObserverMissions(BudgetEntryFields):
    pass


class BudgetCategoryFieldsStationObservers(BudgetEntryFields):
    pass


class BudgetCategoryFieldsStationResearchers(BudgetEntryFields):
    pass


class BudgetCategoryFieldsTradePolicy(BudgetEntryFields):
    pass


BudgetEntryFields.model_rebuild()
BudgetCategoryFields.model_rebuild()
