# Generated by ariadne-codegen
# Source: queries.graphql

from datetime import datetime

from .base_model import BaseModel
from .fragments import BudgetCategoryFields


class GetIncomeExpenses(BaseModel):
    save: GetIncomeExpensesSave | None


class GetIncomeExpensesSave(BaseModel):
    gamestates: list[GetIncomeExpensesSaveGamestates]


class GetIncomeExpensesSaveGamestates(BaseModel):
    date: datetime
    budget: GetIncomeExpensesSaveGamestatesBudget


class GetIncomeExpensesSaveGamestatesBudget(BaseModel):
    income: GetIncomeExpensesSaveGamestatesBudgetIncome
    expenses: GetIncomeExpensesSaveGamestatesBudgetExpenses


class GetIncomeExpensesSaveGamestatesBudgetIncome(BudgetCategoryFields):
    pass


class GetIncomeExpensesSaveGamestatesBudgetExpenses(BudgetCategoryFields):
    pass


GetIncomeExpenses.model_rebuild()
GetIncomeExpensesSave.model_rebuild()
GetIncomeExpensesSaveGamestates.model_rebuild()
GetIncomeExpensesSaveGamestatesBudget.model_rebuild()
