# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Any, Optional

from .base_model import BaseModel


class GetDates(BaseModel):
    save: Optional["GetDatesSave"]


class GetDatesSave(BaseModel):
    gamestates: list["GetDatesSaveGamestates"]


class GetDatesSaveGamestates(BaseModel):
    date: Any


GetDates.model_rebuild()
GetDatesSave.model_rebuild()
