# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Any, Optional

from .base_model import BaseModel
from .fragments import BudgetCategoryFields


class GetBudget(BaseModel):
    save: Optional["GetBudgetSave"]


class GetBudgetSave(BaseModel):
    gamestates: list["GetBudgetSaveGamestates"]


class GetBudgetSaveGamestates(BaseModel):
    date: Any
    budget: "GetBudgetSaveGamestatesBudget"


class GetBudgetSaveGamestatesBudget(BaseModel):
    balance: "GetBudgetSaveGamestatesBudgetBalance"


class GetBudgetSaveGamestatesBudgetBalance(BudgetCategoryFields):
    pass


GetBudget.model_rebuild()
GetBudgetSave.model_rebuild()
GetBudgetSaveGamestates.model_rebuild()
GetBudgetSaveGamestatesBudget.model_rebuild()
