# Generated by ariadne-codegen
# Source: queries.graphql

from datetime import datetime

from .base_model import BaseModel
from .fragments import BudgetCategoryFields


class GetBudget(BaseModel):
    save: GetBudgetSave | None


class GetBudgetSave(BaseModel):
    gamestates: list[GetBudgetSaveGamestates]


class GetBudgetSaveGamestates(BaseModel):
    date: datetime
    budget: GetBudgetSaveGamestatesBudget


class GetBudgetSaveGamestatesBudget(BaseModel):
    balance: GetBudgetSaveGamestatesBudgetBalance


class GetBudgetSaveGamestatesBudgetBalance(BudgetCategoryFields):
    pass


GetBudget.model_rebuild()
GetBudgetSave.model_rebuild()
GetBudgetSaveGamestates.model_rebuild()
GetBudgetSaveGamestatesBudget.model_rebuild()
