# Generated by ariadne-codegen
# Source: queries.graphql

from datetime import datetime
from typing import Optional

from .base_model import BaseModel


class GetDates(BaseModel):
    save: Optional["GetDatesSave"]


class GetDatesSave(BaseModel):
    gamestates: list["GetDatesSaveGamestates"]


class GetDatesSaveGamestates(BaseModel):
    date: datetime


GetDates.model_rebuild()
GetDatesSave.model_rebuild()
