# Generated by ariadne-codegen
# Source: queries.graphql

from .base_model import BaseModel


class ListSaves(BaseModel):
    saves: list[ListSavesSaves]


class ListSavesSaves(BaseModel):
    filename: str
    name: str


ListSaves.model_rebuild()
